name: Test

on:
  push:
    branches:
      - feature-*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK (Java Development Kit) for Gradle
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Replace with the version of Java required for your Gradle build

      # Run the publishPlugin Gradle task
      - name: Test plugin
        run: ./gradlew test
